Created Output Log File: /workdir/tasks_run/data/logs/data_dictionary_20240911_14h42m47s.csv
====== whole_session_data ======
script_starting_time,2024-09-11 14:42:35.950988
sambashare_dir_path,/workdir/tasks_run/data/sambashare
roi_mask_dir_path,/workdir/tasks_run/data/roi_masks
log_directory_path,/workdir/tasks_run/data/logs
starting_block,1
number_of_trials,140
retries_before_ending,3
output_text_logfile_path,/workdir/tasks_run/data/logs/calculator_script_20240911_14h42m35s.txt
roi_mask_path,/workdir/tasks_run/data/roi_masks/P004_e3_registered_rifg.nii
dicom_dir_path,/workdir/tasks_run/data/sambashare/test_dir
starting_dicoms_in_dir,216
dicoms_in_dir,221
scripting_ending_time,2024-09-11 14:42:47.678155
script_total_time,0:00:11.727169
script_ending_cause,keyboard interrupt
====== block1 ======
block_start_time,2024-09-11 14:42:35.955559
num_trials_failed,0
nii_list,[]
event_dict,{}
resid_list,[]
nf_scores,[]
====== trial1 ======
trial_start_time,2024-09-11 14:42:35.958586
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/20075901646001633173.dcm
errors,"[('time_of_error: 20240911_14h42m40s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 93, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h42m40s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 93, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n')]"
this_trial_tries,2
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR1.nii
mean_activation,432.0825
successful_trial_end,True
ending_trial_time,2024-09-11 14:42:41.459375
total_trial_time,0:00:05.500794
====== trial2 ======
trial_start_time,2024-09-11 14:42:41.462363
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/38044286441506574977.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR2.nii
mean_activation,431.4536
successful_trial_end,True
ending_trial_time,2024-09-11 14:42:42.518756
total_trial_time,0:00:01.056400
====== trial3 ======
trial_start_time,2024-09-11 14:42:42.522236
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/64015594965580540858.dcm
errors,"[('time_of_error: 20240911_14h42m43s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 93, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n'), ('time_of_error: 20240911_14h42m43s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 27, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 93, in run_trial\n    dictionary[f""block{block}""][f""trial{trial}""][""nifti_path""] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)\n  File ""/workdir/tasks_run/scripts/file_handler.py"", line 69, in dicom_to_nifti\n    raise Exception(""Cannot Find Nifti Image After dcm2niix"")\nException: Cannot Find Nifti Image After dcm2niix\n')]"
this_trial_tries,2
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR3.nii
mean_activation,434.17578
successful_trial_end,True
ending_trial_time,2024-09-11 14:42:44.636516
total_trial_time,0:00:02.114285
====== trial4 ======
trial_start_time,2024-09-11 14:42:44.639541
keyboard_interrupt,2024-09-11 14:42:46.473254
block_end_time,2024-09-11 14:42:47.675156
total_block_time,0:00:11.719600
