Created Output Log File: /workdir/tasks_run/data/nfb_logs/p004_data_dictionary_20240912_14h07m39s.csv
====== whole_session_data ======
script_starting_time,2024-09-12 14:07:29.883269
sambashare_dir_path,/workdir/tasks_run/data/sambashare
starting_block,1
retries_before_ending,3
pid,p004
dicom_dir_path,/workdir/tasks_run/data/sambashare/test_dir
output_text_logfile_path,/workdir/tasks_run/data/nfb_logs/p004_calculator_script_20240912_14h07m29s.txt
roi_mask_dir_path,/workdir/tasks_run/data/roi_masks
roi_mask_path,/workdir/tasks_run/data/roi_masks/P004_e3_registered_rifg.nii
log_directory_path,/workdir/tasks_run/data/nfb_logs
number_of_trials,140
starting_dicoms_in_dir,5
dicoms_in_dir,9
experimenter_screen_width,3390
experimenter_screen_height,1080
second_monitor_width,1920
second_monitor_height,1080
monitor_X_OFFSET,1920
monitor_Y_OFFSET,0
fixation_width,200
fixation_height,200
scripting_ending_time,2024-09-12 14:07:39.732013
script_total_time,0:00:09.848760
script_ending_cause,keyboard interrupt
====== block1 ======
block_start_time,2024-09-12 14:07:33.800482
num_trials_failed,0
nii_list,[]
event_dict,{}
resid_list,[]
nf_scores,[]
====== trial1 ======
trial_start_time,2024-09-12 14:07:33.817900
this_trial_tries,4
dicom_path,/workdir/tasks_run/data/sambashare/test_dir/17369317810766909646.dcm
nifti_path,/workdir/tasks_run/data/nifti_tmpdir/nii_TR1.nii
mean_activation,186.99771
errors,"[('time_of_error: 20240912_14h07m33s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/ScriptManager.py"", line 28, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 26, in run_trial\n    dictionary = Calculator.get_resid(dictionary=dictionary, block=block, trial=trial)\n  File ""/workdir/tasks_run/scripts/Calculator.py"", line 78, in get_resid\n    subprocess.run([\'gzip\', \'-c\', nii_img, \'>\', nii_gz_img])  # compress image to .nii.gz\n  File ""/usr/local/lib/python3.10/subprocess.py"", line 503, in run\n    with Popen(*popenargs, **kwargs) as process:\n  File ""/usr/local/lib/python3.10/subprocess.py"", line 971, in __init__\n    self._execute_child(args, executable, preexec_fn, close_fds,\n  File ""/usr/local/lib/python3.10/subprocess.py"", line 1780, in _execute_child\n    self.pid = _posixsubprocess.fork_exec(\nTypeError: expected str, bytes or os.PathLike object, not Nifti1Image\n'), ('time_of_error: 20240912_14h07m34s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/ScriptManager.py"", line 28, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 26, in run_trial\n    dictionary = Calculator.get_resid(dictionary=dictionary, block=block, trial=trial)\n  File ""/workdir/tasks_run/scripts/Calculator.py"", line 78, in get_resid\n    subprocess.run([\'gzip\', \'-c\', nii_img, \'>\', nii_gz_img])  # compress image to .nii.gz\n  File ""/usr/local/lib/python3.10/subprocess.py"", line 503, in run\n    with Popen(*popenargs, **kwargs) as process:\n  File ""/usr/local/lib/python3.10/subprocess.py"", line 971, in __init__\n    self._execute_child(args, executable, preexec_fn, close_fds,\n  File ""/usr/local/lib/python3.10/subprocess.py"", line 1780, in _execute_child\n    self.pid = _posixsubprocess.fork_exec(\nTypeError: expected str, bytes or os.PathLike object, not Nifti1Image\n'), ('time_of_error: 20240912_14h07m34s', 'Traceback (most recent call last):\n  File ""/workdir/tasks_run/scripts/ScriptManager.py"", line 28, in wrapper\n    updated_dictionary = func(*args, **kwargs)\n  File ""/workdir/tasks_run/scripts/nf_calc_MW.py"", line 26, in run_trial\n    dictionary = Calculator.get_resid(dictionary=dictionary, block=block, trial=trial)\n  File ""/workdir/tasks_run/scripts/Calculator.py"", line 78, in get_resid\n    subprocess.run([\'gzip\', \'-c\', nii_img, \'>\', nii_gz_img])  # compress image to .nii.gz\n  File ""/usr/local/lib/python3.10/subprocess.py"", line 503, in run\n    with Popen(*popenargs, **kwargs) as process:\n  File ""/usr/local/lib/python3.10/subprocess.py"", line 971, in __init__\n    self._execute_child(args, executable, preexec_fn, close_fds,\n  File ""/usr/local/lib/python3.10/subprocess.py"", line 1780, in _execute_child\n    self.pid = _posixsubprocess.fork_exec(\nTypeError: expected str, bytes or os.PathLike object, not Nifti1Image\n')]"
failed_dicoms,"['/workdir/tasks_run/data/sambashare/test_dir/95907927929285857075.dcm', '/workdir/tasks_run/data/sambashare/test_dir/82735067070452218944.dcm']"
keyboard_interrupt,2024-09-12 14:07:35.742596
num_trials_with_errors,3
block_end_time,2024-09-12 14:07:39.724997
total_block_time,0:00:05.924523
