Created Output Log File: /workdir/tasks_run/data/logs/calculator_script_20240910_16h10m25s.txtdicom dir using: /workdir/tasks_run/data/sambashare/test_dir
Starting Block1 ... 
========================================
Starting Block1, Trial 1... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/34941477771739166189.dcm
nii_img_dtpye: int16
Mean ROI Activation: 415.5724792480469
Error:
'list' object has no attribute 'get_data_dtype'
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc.py", line 82, in run_trial
    dictionary = calculations.get_resid(dictionary=dictionary, block=block, trial=trial)
  File "/workdir/tasks_run/scripts/calculations.py", line 37, in get_resid
    niiList: list = dictionary[f"block{block}"]["nii_list"].get_data_dtype(),
AttributeError: 'list' object has no attribute 'get_data_dtype'

Retries left: 2
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/34941477771739166189.dcm
nii_img_dtpye: int16
Mean ROI Activation: 415.5724792480469
Error:
'list' object has no attribute 'get_data_dtype'
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc.py", line 82, in run_trial
    dictionary = calculations.get_resid(dictionary=dictionary, block=block, trial=trial)
  File "/workdir/tasks_run/scripts/calculations.py", line 37, in get_resid
    niiList: list = dictionary[f"block{block}"]["nii_list"].get_data_dtype(),
AttributeError: 'list' object has no attribute 'get_data_dtype'

Retries left: 1
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/34941477771739166189.dcm
nii_img_dtpye: int16
Mean ROI Activation: 415.5724792480469
Error:
'list' object has no attribute 'get_data_dtype'
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc.py", line 82, in run_trial
    dictionary = calculations.get_resid(dictionary=dictionary, block=block, trial=trial)
  File "/workdir/tasks_run/scripts/calculations.py", line 37, in get_resid
    niiList: list = dictionary[f"block{block}"]["nii_list"].get_data_dtype(),
AttributeError: 'list' object has no attribute 'get_data_dtype'

Retries left: 0
Ran out of retries. Skipping this trial.
Ending Block1, Trial 1... 
========================================
Starting Block1, Trial 2... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/44621561576607638106.dcm
nii_img_dtpye: int16
Mean ROI Activation: 414.5749816894531
Error:
'list' object has no attribute 'get_data_dtype'
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc.py", line 82, in run_trial
    dictionary = calculations.get_resid(dictionary=dictionary, block=block, trial=trial)
  File "/workdir/tasks_run/scripts/calculations.py", line 37, in get_resid
    niiList: list = dictionary[f"block{block}"]["nii_list"].get_data_dtype(),
AttributeError: 'list' object has no attribute 'get_data_dtype'

Retries left: 2
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/44621561576607638106.dcm
nii_img_dtpye: int16
Mean ROI Activation: 414.5749816894531
Error:
'list' object has no attribute 'get_data_dtype'
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc.py", line 82, in run_trial
    dictionary = calculations.get_resid(dictionary=dictionary, block=block, trial=trial)
  File "/workdir/tasks_run/scripts/calculations.py", line 37, in get_resid
    niiList: list = dictionary[f"block{block}"]["nii_list"].get_data_dtype(),
AttributeError: 'list' object has no attribute 'get_data_dtype'

Retries left: 1
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/44621561576607638106.dcm
nii_img_dtpye: int16
Mean ROI Activation: 414.5749816894531
Error:
'list' object has no attribute 'get_data_dtype'
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc.py", line 82, in run_trial
    dictionary = calculations.get_resid(dictionary=dictionary, block=block, trial=trial)
  File "/workdir/tasks_run/scripts/calculations.py", line 37, in get_resid
    niiList: list = dictionary[f"block{block}"]["nii_list"].get_data_dtype(),
AttributeError: 'list' object has no attribute 'get_data_dtype'

Retries left: 0
Ran out of retries. Skipping this trial.
Ending Block1, Trial 2... 
========================================
Starting Block1, Trial 3... 
========================================
Waiting For New File ...
---- Keyboard Interrupt Detected ----
What Would You Like to Do?
(1) Continue With The Block
(2) End The Session
(3) Start New Block
Ok, Let's End the Session...
Nifti Outdir Cleared
Ending Session Due to: keyboard interrupt
Session Data:
Running Main Calculation Script ... 
