Created Output Log File: /workdir/tasks_run/data/logs/calculator_script_20240910_16h06m45s.txtdicom dir using: /workdir/tasks_run/data/sambashare/test_dir
Starting Block1 ... 
========================================
Starting Block1, Trial 1... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/79281865656821150076.dcm
nii_img_dtpye: int16
Mean ROI Activation: 415.5724792480469
Error:
Input data has incompatible dimensionality: Expected dimension is 3D and you provided a list of 3D images (4D). See https://nilearn.github.io/stable/manipulating_images/input_output.html.
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc.py", line 82, in run_trial
    dictionary = calculations.get_resid(dictionary=dictionary, block=block, trial=trial)
  File "/workdir/tasks_run/scripts/calculations.py", line 46, in get_resid
    masker.fit()
  File "/usr/local/lib/python3.10/site-packages/nilearn/maskers/nifti_masker.py", line 428, in fit
    self.mask_img_ = _utils.check_niimg_3d(self.mask_img)
  File "/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py", line 371, in check_niimg_3d
    return check_niimg(niimg, ensure_ndim=3, dtype=dtype)
  File "/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py", line 313, in check_niimg
    return concat_niimgs(niimg, ensure_ndim=ensure_ndim, dtype=dtype)
  File "/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py", line 490, in concat_niimgs
    first_niimg = check_niimg(next(literator), ensure_ndim=ndim)
  File "/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py", line 329, in check_niimg
    raise DimensionError(len(niimg.shape), ensure_ndim)
nilearn._utils.exceptions.DimensionError: Input data has incompatible dimensionality: Expected dimension is 3D and you provided a list of 3D images (4D). See https://nilearn.github.io/stable/manipulating_images/input_output.html.

Retries left: 2
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/79281865656821150076.dcm
nii_img_dtpye: int16
Mean ROI Activation: 415.5724792480469
Error:
Input data has incompatible dimensionality: Expected dimension is 3D and you provided a list of 3D images (4D). See https://nilearn.github.io/stable/manipulating_images/input_output.html.
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc.py", line 82, in run_trial
    dictionary = calculations.get_resid(dictionary=dictionary, block=block, trial=trial)
  File "/workdir/tasks_run/scripts/calculations.py", line 46, in get_resid
    masker.fit()
  File "/usr/local/lib/python3.10/site-packages/nilearn/maskers/nifti_masker.py", line 428, in fit
    self.mask_img_ = _utils.check_niimg_3d(self.mask_img)
  File "/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py", line 371, in check_niimg_3d
    return check_niimg(niimg, ensure_ndim=3, dtype=dtype)
  File "/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py", line 313, in check_niimg
    return concat_niimgs(niimg, ensure_ndim=ensure_ndim, dtype=dtype)
  File "/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py", line 490, in concat_niimgs
    first_niimg = check_niimg(next(literator), ensure_ndim=ndim)
  File "/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py", line 329, in check_niimg
    raise DimensionError(len(niimg.shape), ensure_ndim)
nilearn._utils.exceptions.DimensionError: Input data has incompatible dimensionality: Expected dimension is 3D and you provided a list of 3D images (4D). See https://nilearn.github.io/stable/manipulating_images/input_output.html.

Retries left: 1
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/79281865656821150076.dcm
nii_img_dtpye: int16
Mean ROI Activation: 415.5724792480469
Error:
Input data has incompatible dimensionality: Expected dimension is 3D and you provided a list of 3D images (4D). See https://nilearn.github.io/stable/manipulating_images/input_output.html.
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc.py", line 82, in run_trial
    dictionary = calculations.get_resid(dictionary=dictionary, block=block, trial=trial)
  File "/workdir/tasks_run/scripts/calculations.py", line 46, in get_resid
    masker.fit()
  File "/usr/local/lib/python3.10/site-packages/nilearn/maskers/nifti_masker.py", line 428, in fit
    self.mask_img_ = _utils.check_niimg_3d(self.mask_img)
  File "/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py", line 371, in check_niimg_3d
    return check_niimg(niimg, ensure_ndim=3, dtype=dtype)
  File "/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py", line 313, in check_niimg
    return concat_niimgs(niimg, ensure_ndim=ensure_ndim, dtype=dtype)
  File "/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py", line 490, in concat_niimgs
    first_niimg = check_niimg(next(literator), ensure_ndim=ndim)
  File "/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py", line 329, in check_niimg
    raise DimensionError(len(niimg.shape), ensure_ndim)
nilearn._utils.exceptions.DimensionError: Input data has incompatible dimensionality: Expected dimension is 3D and you provided a list of 3D images (4D). See https://nilearn.github.io/stable/manipulating_images/input_output.html.

Retries left: 0
Ran out of retries. Skipping this trial.
Ending Block1, Trial 1... 
========================================
Starting Block1, Trial 2... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/59940179487107070521.dcm
nii_img_dtpye: int16
Mean ROI Activation: 414.5749816894531
Error:
Input data has incompatible dimensionality: Expected dimension is 3D and you provided a list of 3D images (4D). See https://nilearn.github.io/stable/manipulating_images/input_output.html.
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc.py", line 82, in run_trial
    dictionary = calculations.get_resid(dictionary=dictionary, block=block, trial=trial)
  File "/workdir/tasks_run/scripts/calculations.py", line 46, in get_resid
    masker.fit()
  File "/usr/local/lib/python3.10/site-packages/nilearn/maskers/nifti_masker.py", line 428, in fit
    self.mask_img_ = _utils.check_niimg_3d(self.mask_img)
  File "/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py", line 371, in check_niimg_3d
    return check_niimg(niimg, ensure_ndim=3, dtype=dtype)
  File "/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py", line 313, in check_niimg
    return concat_niimgs(niimg, ensure_ndim=ensure_ndim, dtype=dtype)
  File "/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py", line 490, in concat_niimgs
    first_niimg = check_niimg(next(literator), ensure_ndim=ndim)
  File "/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py", line 329, in check_niimg
    raise DimensionError(len(niimg.shape), ensure_ndim)
nilearn._utils.exceptions.DimensionError: Input data has incompatible dimensionality: Expected dimension is 3D and you provided a list of 3D images (4D). See https://nilearn.github.io/stable/manipulating_images/input_output.html.

Retries left: 2
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/59940179487107070521.dcm
nii_img_dtpye: int16
Mean ROI Activation: 414.5749816894531
Error:
Input data has incompatible dimensionality: Expected dimension is 3D and you provided a list of 3D images (4D). See https://nilearn.github.io/stable/manipulating_images/input_output.html.
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc.py", line 82, in run_trial
    dictionary = calculations.get_resid(dictionary=dictionary, block=block, trial=trial)
  File "/workdir/tasks_run/scripts/calculations.py", line 46, in get_resid
    masker.fit()
  File "/usr/local/lib/python3.10/site-packages/nilearn/maskers/nifti_masker.py", line 428, in fit
    self.mask_img_ = _utils.check_niimg_3d(self.mask_img)
  File "/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py", line 371, in check_niimg_3d
    return check_niimg(niimg, ensure_ndim=3, dtype=dtype)
  File "/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py", line 313, in check_niimg
    return concat_niimgs(niimg, ensure_ndim=ensure_ndim, dtype=dtype)
  File "/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py", line 490, in concat_niimgs
    first_niimg = check_niimg(next(literator), ensure_ndim=ndim)
  File "/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py", line 329, in check_niimg
    raise DimensionError(len(niimg.shape), ensure_ndim)
nilearn._utils.exceptions.DimensionError: Input data has incompatible dimensionality: Expected dimension is 3D and you provided a list of 3D images (4D). See https://nilearn.github.io/stable/manipulating_images/input_output.html.

Retries left: 1
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/59940179487107070521.dcm
nii_img_dtpye: int16
Mean ROI Activation: 414.5749816894531
Error:
Input data has incompatible dimensionality: Expected dimension is 3D and you provided a list of 3D images (4D). See https://nilearn.github.io/stable/manipulating_images/input_output.html.
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc.py", line 82, in run_trial
    dictionary = calculations.get_resid(dictionary=dictionary, block=block, trial=trial)
  File "/workdir/tasks_run/scripts/calculations.py", line 46, in get_resid
    masker.fit()
  File "/usr/local/lib/python3.10/site-packages/nilearn/maskers/nifti_masker.py", line 428, in fit
    self.mask_img_ = _utils.check_niimg_3d(self.mask_img)
  File "/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py", line 371, in check_niimg_3d
    return check_niimg(niimg, ensure_ndim=3, dtype=dtype)
  File "/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py", line 313, in check_niimg
    return concat_niimgs(niimg, ensure_ndim=ensure_ndim, dtype=dtype)
  File "/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py", line 490, in concat_niimgs
    first_niimg = check_niimg(next(literator), ensure_ndim=ndim)
  File "/usr/local/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py", line 329, in check_niimg
    raise DimensionError(len(niimg.shape), ensure_ndim)
nilearn._utils.exceptions.DimensionError: Input data has incompatible dimensionality: Expected dimension is 3D and you provided a list of 3D images (4D). See https://nilearn.github.io/stable/manipulating_images/input_output.html.

Retries left: 0
Ran out of retries. Skipping this trial.
Ending Block1, Trial 2... 
========================================
Starting Block1, Trial 3... 
========================================
Waiting For New File ...
---- Keyboard Interrupt Detected ----
What Would You Like to Do?
(1) Continue With The Block
(2) End The Session
(3) Start New Block
Running Main Calculation Script ... 
