Created Output Log File: /workdir/tasks_run/data/logs/calculator_script_20240911_14h27m19s.txtdicom dir using: /workdir/tasks_run/data/sambashare/test_dir
Starting Block1 ... 
========================================
Starting Block1, Trial 1... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/93303414827030448094.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 90, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 3
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/93303414827030448094.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 90, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 2
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/93303414827030448094.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 90, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 1
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/93303414827030448094.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 90, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 0
Ran out of retries. Skipping this trial.
Ending Block1, Trial 1... 
========================================
Starting Block1, Trial 2... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/11622520407786268170.dcm
nii_img_dtpye: int16
Mean ROI Activation: 432.0824890136719
Ending Block1, Trial 2... 
========================================
Starting Block1, Trial 3... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/36983343217454900398.dcm
nii_img_dtpye: int16
Mean ROI Activation: 431.45361328125
Ending Block1, Trial 3... 
========================================
Starting Block1, Trial 4... 
========================================
Waiting For New File ...
New File Found In Dir...
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/53719175334178132689.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 90, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 3
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/53719175334178132689.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 90, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 2
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/53719175334178132689.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 90, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 1
Using DICOM:/workdir/tasks_run/data/sambashare/test_dir/53719175334178132689.dcm
Error:
Cannot Find Nifti Image After dcm2niix
Traceback (most recent call last):
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 27, in wrapper
    updated_dictionary = func(*args, **kwargs)
  File "/workdir/tasks_run/scripts/nf_calc_MW.py", line 90, in run_trial
    dictionary[f"block{block}"][f"trial{trial}"]["nifti_path"] = file_handler.dicom_to_nifti(dicom_file=dicom_path, trial=trial)
  File "/workdir/tasks_run/scripts/file_handler.py", line 69, in dicom_to_nifti
    raise Exception("Cannot Find Nifti Image After dcm2niix")
Exception: Cannot Find Nifti Image After dcm2niix

Retries left: 0
Ran out of retries. Skipping this trial.
Ending Block1, Trial 4... 
========================================
Starting Block1, Trial 5... 
========================================
Waiting For New File ...
---- Keyboard Interrupt Detected ----
What Would You Like to Do?
(1) Continue With The Block
(2) End The Session
(3) Start New Block
Ok, Let's End the Session...
Nifti Outdir Cleared
Ending Session Due to: keyboard interrupt
Session Data:
Running Main Calculation Script ... 
